#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

ASSETS=$(cd "$(dirname "$0")" && pwd)
source $ASSETS/helpers/git.sh
source $ASSETS/helpers/utils.sh
source $ASSETS/helpers/bitbucket.sh

# for all temporary files in 'check'
tmpfile() {
  tmp_file "check-$1"
}

# for jq
PATH=/usr/local/bin:$PATH

payload=$(tmpfile request)

cat > "$payload" <&0

log "Configuring git credentials"
load_pubkey "$payload"

configure_credentials "$payload"

log "Parsing payload"
uri=$(jq -r '.source.uri // ""' < "$payload")
skip_ssl_verification=$(jq -r '.source.skip_ssl_verification // false' < ${payload})
git_config_payload=$(jq -r '.source.git_config // []' < "$payload")

only_for_branch=$(jq -r '.source.only_for_branch // "."' < "$payload")
only_without_conflicts=$(jq -r '.source.only_without_conflicts // "true"' < "$payload")
only_when_mergeable=$(jq -r '.source.only_when_mergeable // "false"' < "$payload")
only_when_asked=$(jq -r '.source.only_when_asked // "false"' < "$payload")
sleep_between_fetches=$(jq -r '.source.sleep_between_fetches // "0"' < "$payload")
  sleep_between_fetches=$(echo "$sleep_between_fetches" | sed 's/[^0-9\.]//g')
rebuild_when_target_changed=$(jq -r '.source.rebuild_when_target_changed // "false"' < "$payload")
rebuild_phrase=$(jq -r '.source.rebuild_phrase // "test this please"' < "$payload")
CURRENT_VERSION_DATE=$(jq -r '.version.date // "0"' < "$payload")

configure_git_ssl_verification "$skip_ssl_verification"
configure_git_global "${git_config_payload}"

if [ -z "$uri" ]; then
  log "invalid payload (missing uri):" "$(cat $payload)"
  exit 1
fi

# if option 'rebuild_when_target_changed' is enabled take merge branch since commit will always change for changes on target branch
prq_branch="from"
if [ "$rebuild_when_target_changed" == "true" ]; then
  prq_branch="merge"
fi

# collect all pull requests from uri
REMOTES=$(git ls-remote "$uri")
set +e
PULL_REQUESTS=$(echo "$REMOTES" | grep -E "/pull\\-requests/[0-9]+/${prq_branch}")
set -e


versions="[]"
if [ -n "$PULL_REQUESTS" ]; then
  log "Calculating repository specifics"
  # determine repository name for calling REST api
  repo_name=$(basename "$uri" | sed "s/.git$//")
  repo_project=$(basename $(dirname "$uri"))

  # parse uri and retrieve host
  uri_parser "$uri"
  repo_host="${uri_schema}://${uri_address}"

  repo_host=${repo_host}$(getBasePathOfBitbucket)

  versions="[]"
  while read pull_request ; do
    sleep $sleep_between_fetches  # throttle requests to avoid excessive load to server
    log "Verifying pull request"
    # determine hash and prq number from grep
    prq_number=$(echo "$pull_request" | sed -E "s/^.*\/pull-requests\/([0-9]+)\/.*$/\\1/")
    prq_hash=$(echo "$pull_request" | awk '{print $1}')

    # verify target branch of prq
    prq=$(bitbucket_pullrequest "$repo_host" "$repo_project" "$repo_name" "$prq_number" "" "$skip_ssl_verification")

    if [ "$prq" = "NO_SUCH_PULL_REQUEST" ]; then
      continue
    fi

    PULL_REQUEST_DATE=$(echo "$prq" | jq -r '.updatedDate')

    log "Pull request #${prq_number}"

    prq_to_branch=$(echo "$prq" | jq -r '.toRef.displayId')
    if [[ "$prq_to_branch" =~ $only_for_branch ]]; then

      if [ "$only_when_mergeable" == "true" -o "$only_without_conflicts" == "true" ]; then
        prq_merge=$(bitbucket_pullrequest_merge "$repo_host" "$repo_project" "$repo_name" "$prq_number" "" "$skip_ssl_verification")

        if [ "$prq_merge" = "ALREADY_MERGED" ] || [ "$prq_merge" = "DECLINED" ]; then
          continue
        fi

        # verify if prq has merge conflicts
        conflicted=$(echo "$prq_merge" | jq -r '.conflicted')
        if [ "$conflicted" == "true" -a "$only_without_conflicts" == "true" ]; then continue; fi

        # verify if prq is mergeable (e.g. enough approvals, tasks done, ...)
        mergeable=$(echo "$prq_merge" | jq -r '.canMerge')
        if [ "$mergeable" == "false" -a "$only_when_mergeable" == "true" ]; then continue; fi
      fi

      # edit timestamp to version to force new build when rebuild_phrase is included in comments
      skip_build=false
      comments=$(bitbucket_pullrequest_overview_comments "$repo_host" "$repo_project" "$repo_name" "$prq_number" "" "$skip_ssl_verification" | jq -c '.[]')
      if [ -n "$comments" ]; then
        while read -r comment; do
          text=$(echo "$comment" | jq -r '.text')

          # check for progress or finished messages => do not include in versions when available
          if bitbucket_pullrequest_comment_commit_match "$text" "$prq_hash"; then
            log "Skipping PRQ #$prq_number since already handled"
            skip_build=true
            break
          fi

          # edit timestamp to force new build when rebuild_phrase is included in comments
          if echo "$text" | grep -Ec "$rebuild_phrase" > /dev/null; then
            PULL_REQUEST_DATE=$(echo "$comment" | jq -r '.createdDate')
            break
          fi
        done <<< "$comments"
      fi

      if [ "$PULL_REQUEST_DATE" -lt "$CURRENT_VERSION_DATE" ]; then
        continue
      fi

      # add prq to versions
      if [ "$skip_build" == "false" ]; then
        versions+=" + [{ id: \"$prq_number\", hash: \"$prq_hash\", date: \"$PULL_REQUEST_DATE\" }]"
      fi
    fi
  done <<< "$PULL_REQUESTS"
fi

# On the first request return only the current version.
if [ "$CURRENT_VERSION_DATE" -eq "0" ]; then
  jq -n "$versions | sort_by((.date | tonumber), (.id | tonumber), .hash) | .[-1:]" > /tmp/check_result
else
  jq -n "$versions | sort_by((.date | tonumber), (.id | tonumber), .hash)" > /tmp/check_result
fi

cat /tmp/check_result >&3
