#!/bin/bash

set -eu

set +e
docker run --interactive --rm hadolint/hadolint < Dockerfile
docker run --interactive --rm --volume "$PWD:/mnt" koalaman/shellcheck \
  --color=always \
  /mnt/assets/check \
  /mnt/assets/helpers/askpass.sh \
  /mnt/assets/helpers/bitbucket.sh \
  /mnt/assets/helpers/git.sh \
  /mnt/assets/helpers/utils.sh \
  /mnt/assets/in \
  /mnt/assets/out \
  /mnt/install_git_lfs.sh \
  /mnt/scripts/test
set -e

docker build --pull --rm --tag mm62/concourse-bitbucket-pullrequest-resource-test .
docker rmi mm62/concourse-bitbucket-pullrequest-resource-test
